const fetchRecipes = () => {
    return [
        {
          img: './assets/image8.png',
          duration: 30,
          rating: 4,
          isVideo: true,
          title: 'Zalogajčići od banana i maslaca od kikirikija',
          category: 'GLAVNA JELA',
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.'
        },
        {
          img: './assets/image9.png',
          duration: 30,
          rating: 4,
          isVideo: true,
          title: 'Zafrkanci s makom',
          category: 'DESERTI',
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna ...',
        },
        {
          img: './assets/image10.png',
          duration: 30,
          rating: 4,
          isVideo: false,
          title: 'Piletina s perecima u umaku od senfa i cheddar sira',
          category: 'DORUCAK',
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna ...',
        },
        {
          img: './assets/image8.png',
          duration: 30,
          rating: 4,
          isVideo: true,
          title: 'Zalogajčići od banana i maslaca od kikirikija',
          category: 'GLAVNA JELA',
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.'
        },
        {
          img: './assets/image9.png',
          duration: 30,
          rating: 4,
          isVideo: true,
          title: 'Zafrkanci s makom',
          category: 'DESERTI',
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna ...',
        },
        {
          img: './assets/image10.png',
          duration: 30,
          rating: 4,
          isVideo: false,
          title: 'Piletina s perecima u umaku od senfa i cheddar sira',
          category: 'DORUCAK',
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna ...',
        },
        {
          img: './assets/image8.png',
          duration: 30,
          rating: 4,
          isVideo: true,
          title: 'Zalogajčići od banana i maslaca od kikirikija',
          category: 'GLAVNA JELA',
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.'
        },
        {
          img: './assets/image9.png',
          duration: 30,
          rating: 4,
          isVideo: true,
          title: 'Zafrkanci s makom',
          category: 'DESERTI',
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna ...',
        },
        {
          img: './assets/image10.png',
          duration: 30,
          rating: 4,
          isVideo: false,
          title: 'Piletina s perecima u umaku od senfa i cheddar sira',
          category: 'DORUCAK',
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna ...',
        },
        {
          img: './assets/image8.png',
          duration: 30,
          rating: 4,
          isVideo: true,
          title: 'Zalogajčići od banana i maslaca od kikirikija',
          category: 'GLAVNA JELA',
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.'
        },
        {
          img: './assets/image9.png',
          duration: 30,
          rating: 4,
          isVideo: true,
          title: 'Zafrkanci s makom',
          category: 'DESERTI',
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna ...',
        },
        {
          img: './assets/image10.png',
          duration: 30,
          rating: 4,
          isVideo: false,
          title: 'Piletina s perecima u umaku od senfa i cheddar sira',
          category: 'DORUCAK',
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna ...',
        },
    ];
}